-- MySQL Script generated by MySQL Workbench
-- Thu Feb 16 16:25:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema futanalyzer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `futanalyzer` ;

-- -----------------------------------------------------
-- Schema futanalyzer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futanalyzer` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `futanalyzer` ;

-- -----------------------------------------------------
-- Table `futanalyzer`.`jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futanalyzer`.`jogador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `futanalyzer`.`jogador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `overall` INT(11) NOT NULL,
  `gols` INT(11) NULL DEFAULT NULL,
  `Usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `futanalyzer`.`jogador_jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futanalyzer`.`jogador_jogo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `futanalyzer`.`jogador_jogo` (
  `jogo_id` INT(11) NOT NULL,
  `jogador_id` INT(11) NOT NULL,
  `golspjogo` VARCHAR(45) NULL,
  PRIMARY KEY (`jogo_id`, `jogador_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `futanalyzer`.`jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futanalyzer`.`jogo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `futanalyzer`.`jogo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `placarMeu` INT(11) NOT NULL,
  `placarAdv` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `futanalyzer`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futanalyzer`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `futanalyzer`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
