/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelDominio.Jogo;

/**
 *
 * @author gabif
 */
public class FormCadastrodePartidas extends javax.swing.JDialog {

    private int codigo = -1;
    
    public FormCadastrodePartidas(Jogo jogo) {
        initComponents();
        if(jogo == null){
            codigo = -1;
            jBExcluir.setEnabled(false);
        } else {
            codigo = jogo.getId();
            jTFGolsMeuTime.setText(""+ jogo.getMeuPlacar());
            jTFGolsOponente.setText("" + jogo.getAdvPlacar());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome = new javax.swing.JLabel();
        jLOverall = new javax.swing.JLabel();
        jTFGolsMeuTime = new javax.swing.JTextField();
        jTFGolsOponente = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLNome.setText("Meu Time");

        jLOverall.setText("Oponente");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLOverall)
                            .addComponent(jLNome))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFGolsMeuTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFGolsOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBExcluir)
                        .addGap(64, 64, 64)
                        .addComponent(jBSalvar)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBVoltar)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFGolsMeuTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLOverall)
                    .addComponent(jTFGolsOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBSalvar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        int certeza = JOptionPane.showConfirmDialog(this, "Tem certeza?", this.getTitle(), JOptionPane.YES_NO_OPTION);

        // CASO O USUÁRIO RESPONDA SIM PARA A EXCLUSÃO
        if(certeza == JOptionPane.YES_OPTION){
            Jogo jogo = new Jogo (codigo);
            
            String msg = FutAnalyzer.ccont.jogoExcluir(jogo);
            if(msg.equals("ok")){
                JOptionPane.showMessageDialog(this, "Jogo excluido com sucesso");
                
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível excluir" ,this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:

        //verificando se os campos são válidos
        if(!jTFGolsMeuTime.getText().equals("")){

            if(!jTFGolsOponente.getText().equals("")){

                int meusGols = Integer.parseInt(jTFGolsMeuTime.getText());
                int golsAdv = Integer.parseInt(jTFGolsOponente.getText());
                
                Jogo jogo = new Jogo(0, meusGols, golsAdv, FutAnalyzer.ccont.getUsuarioLogado().getCod());
                
                String msg;
                
                if(codigo == -1){
                    msg = FutAnalyzer.ccont.inserirJogo(jogo);
                    dispose();
                } else {
                    jogo.setId(codigo);
                    dispose();
                    msg = FutAnalyzer.ccont.jogoAlterar(jogo);
                    if (msg.equals("ok")){
                        dispose();
                    }
                }                                             

                //caso servidor responda com ok
                if (msg.equals("ok")) {
                    JOptionPane.showMessageDialog(this, "Jogo cadastrado com sucesso!",
                        this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                    jTFGolsMeuTime.setText("");
                    jTFGolsMeuTime.requestFocus();
                    jTFGolsOponente.setText("");
                    jTFGolsOponente.requestFocus();
                } else {
                    //caso não
                    JOptionPane.showMessageDialog(this, "Jogo não foi cadastrado!",
                        this.getTitle(), JOptionPane.ERROR_MESSAGE);
                    jTFGolsMeuTime.requestFocus();
                    jTFGolsOponente.requestFocus();
                }

            }else{
                JOptionPane.showMessageDialog(this, "ERRO: Preencha o campo 'Meu time'! ",
                    this.getTitle(),JOptionPane.ERROR_MESSAGE);
                jTFGolsOponente.requestFocus();
            }

        }else{
            JOptionPane.showMessageDialog(this, "ERRO: Preencha o campo 'Oponente'!",
                this.getTitle(),JOptionPane.ERROR_MESSAGE);
            jTFGolsMeuTime.requestFocus();
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrodePartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrodePartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrodePartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrodePartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrodePartidas(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLOverall;
    private javax.swing.JTextField jTFGolsMeuTime;
    private javax.swing.JTextField jTFGolsOponente;
    // End of variables declaration//GEN-END:variables
}
