/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import modelDominio.Jogador;
import modelDominio.Jogo;
import view.tableModel.JogadorTableModel;
import view.tableModel.JogoTableModel;

/**
 *
 * @author gabif
 */
public class FormVisualizacaoJogos extends javax.swing.JDialog {

     //TableModel da Tabela de Jogador que será utilizada
    private JogoTableModel jogoModel;
    
    
    /**
     * Creates new form FormArtilheirosEAssistentes
     */
    public FormVisualizacaoJogos() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTJogadores = new javax.swing.JTable();
        jBCadastrar = new javax.swing.JButton();
        jCBResultado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jTJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTJogadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTJogadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTJogadores);

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jCBResultado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Vitórias", "Empates", "Derrotas" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBResultado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBVoltar)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:

        //Criando o formulário de cadastro passando null como parâmetro
        //O formulário de cadastro recebe uma Raça como parâmetro, quando for para editar
        // um registro. Neste caso, estamos adicionando um novo registro.
        FormCadastrodePartidas form = new FormCadastrodePartidas(null);

        // abrindo formulario modal (Só é possível quando o formulário for do tipo JDialog
            form.setModal(true);

            // Como foi setado para o formulário ser MODAL. Aqui o sistema ficará travado
            form.setVisible(true);

            // Quando o usuário fechar o cadastro de Marcas deve-se novamente atualizar a tabela
            atualizarTabela();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTJogadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTJogadoresMouseClicked
        // TODO add your handling code here:
         Jogo jogo = jogoModel.getJogo(jTJogadores.getSelectedRow());
        FormCadastrodePartidas formcad = new FormCadastrodePartidas(jogo);
        formcad.setModal(true);
        formcad.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_jTJogadoresMouseClicked

    
public void atualizarTabela() {
        switch (jCBResultado.getSelectedIndex()){ // verificando o filtro selecionado

            // se o usuário escolheu TODAS (case 1)
            // então chama a lista que possui todos os jogos do Controller 
            // Esse método retorna todos os jogos
            case 1 :
                jogoModel = new JogoTableModel(FutAnalyzer.ccont.jogoLista());
                break;

            case 2: // case 2, a tabela mostrará somente as vitórias 
                jogoModel = new JogoTableModel(FutAnalyzer.ccont.jogoListaVitorias());
                break;

            case 3: //case 3, a tabela mostrará somente os empates
                jogoModel = new JogoTableModel(FutAnalyzer.ccont.jogoListaEmpates());
                break;

            default : //por fim, o default mostra as derrotas
                jogoModel = new JogoTableModel(FutAnalyzer.ccont.jogoListaDerrotas());
        }
        jTJogadores.setModel(jogoModel); //setando o modelo correto para a tabela do formulário
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVisualizacaoJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVisualizacaoJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVisualizacaoJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVisualizacaoJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVisualizacaoJogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCBResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTJogadores;
    // End of variables declaration//GEN-END:variables
}
